MAJOR UPDATE TO BLADE OS 25

diff --git a/trixie/desktop-base/debian/postinst b/trixie/desktop-base/debian/postinst
--- a/trixie/desktop-base/debian/postinst
+++ b/trixie/desktop-base/debian/postinst
@@ -66,11 +66,12 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remov
             desktop-theme \
             /usr/share/desktop-base/$theme-theme $priority
     done << EOF
-emerald 50
+ceratopsian 50
+emerald 40
 EOF
 
     # Use active theme as highest priority for background
-    active_background=/usr/share/desktop-base/active-theme/wallpaper/contents/images/1920x1080.svg
+    active_background=/usr/share/desktop-base/active-theme/wallpaper/contents/images/wallpaper.png
     if [ -e ${active_background} ]; then
         update-alternatives --install \
             /usr/share/images/desktop-base/desktop-background \
@@ -83,7 +84,8 @@ EOF
             desktop-background \
             /usr/share/desktop-base/$theme-theme/wallpaper/contents/images/$filename $priority
     done << EOF
-emerald 1920x1080.svg 65
+ceratopsian wallpaper.png 65
+emerald 1920x1080.svg 50
 EOF
 
     # Set up an alternative for the XML version of the background
@@ -102,6 +104,7 @@ EOF
             desktop-background.xml \
             /usr/share/desktop-base/$theme-theme/wallpaper/gnome-background.xml $priority
     done << EOF
+ceratopsian 40
 emerald 40
 EOF
 
@@ -121,7 +124,8 @@ EOF
             desktop-lockscreen.xml \
             /usr/share/desktop-base/$theme-theme/lockscreen/gnome-background.xml $priority
     done << EOF
-emerald 40
+ceratopsian 40
+emerald 30
 EOF
 
     # Set up an alternative for the wallpaper for Plasma 5/KDE
@@ -139,7 +143,8 @@ EOF
             desktop-plasma5-wallpaper \
             /usr/share/desktop-base/$theme-theme/wallpaper $priority
     done << EOF
-emerald 40
+ceratopsian 40
+emerald 30
 EOF
 
     # Login theme
@@ -155,7 +160,73 @@ EOF
             desktop-login-background \
             /usr/share/desktop-base/$theme-theme/login/$background $priority
     done << EOF
-emerald background.svg 40
+ceratopsian background.svg 40
+emerald background.svg 30
 EOF
+
+    # Set up an alternative for the GRUB background/colors config
+    # Highest priority for active theme
+    # Favor widescreen / hi-res background for efi installations detected
+    # by the presence of grub-efi* packages (not the grub-efi*-bin which don’t
+    # necessary account for grub being the active bootloader).
+    if dpkg-query --list grub-efi* | grep -v "^... grub-efi[^[:space:]]*-bin" | grep -q "^[ih][HUFWti] " ; then
+        echo "grub-efi* packages found, using 16/9 as default grub background ratio"
+        grub_first_ratio="16x9"
+        grub_second_ratio="4x3"
+    else
+        echo "No grub-efi* package found, using 4/3 as default grub background ratio"
+        grub_first_ratio="4x3"
+        grub_second_ratio="16x9"
+    fi
+    active_grub_background=/usr/share/desktop-base/active-theme/grub/grub_background.sh
+    active_grub_first_ratio=/usr/share/desktop-base/active-theme/grub/grub-${grub_first_ratio}.png
+    if [ -e ${active_grub_first_ratio} ] && [ -e ${active_grub_background} ]; then
+        update-alternatives --install \
+            /usr/share/images/desktop-base/desktop-grub.png \
+            desktop-grub ${active_grub_first_ratio} 50 \
+            --slave /usr/share/desktop-base/grub_background.sh \
+            desktop-grub.sh ${active_grub_background}
+    fi
+    active_grub_second_ratio=/usr/share/desktop-base/active-theme/grub/grub-${grub_second_ratio}.png
+    if [ -e ${active_grub_second_ratio} ] && [ -e ${active_grub_background} ]; then
+        update-alternatives --install \
+            /usr/share/images/desktop-base/desktop-grub.png \
+            desktop-grub ${active_grub_second_ratio} 45 \
+            --slave /usr/share/desktop-base/grub_background.sh \
+            desktop-grub.sh ${active_grub_background}
+    fi
+    # Alternatives for theme packages
+    while read theme ratio priority; do
+        update-alternatives --install /usr/share/images/desktop-base/desktop-grub.png \
+            desktop-grub \
+            /usr/share/desktop-base/$theme-theme/grub/grub-$ratio.png $priority \
+            --slave /usr/share/desktop-base/grub_background.sh \
+            desktop-grub.sh \
+            /usr/share/desktop-base/$theme-theme/grub/grub_background.sh
+    done << EOF
+ceratopsian 4x3 40
+ceratopsian 16x9 40
+EOF
+
+    # Apply GRUB background update into /boot
+    # Try detecting active grub packages (so not -doc, -common, -bin) as a hint
+    # that GRUB is being used as bootloader before calling update-grub.
+    # Some people use the *-bin packages without using GRUB as bootloader
+    # (see #851893 for more context).
+    if dpkg-query --list "grub-*" | grep -v "^... grub\(-common\|-emu\|[^[:space:]]*\(-bin\|-doc\)\)" | grep -q "^[ih][HUFWti] " \
+            && which update-grub > /dev/null ; then
+        # Ensure the background image file has actually been written to disc
+        # before updating.
+        sync
+        # Report success whatever grub return status. This is needed at least
+        # in live systems fon installation to succeed (see #850601).
+        # Until we find a better solution like detecting we’re in a live image
+        # and not calling update-grub at all.
+        update-grub || echo "Updating grub failed, report success anyway!"
+    fi
+
+    if which update-initramfs > /dev/null; then
+        update-initramfs -u
+    fi
 
 fi
